# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spl_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11spl_service.proto\x12\x03spl\"\"\n\x0f\x46indItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"Q\n\x10\x46indItemResponse\x12\x1d\n\x04item\x18\x01 \x01(\x0b\x32\x0f.spl.ItemObject\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\xcb\x01\n\nItemObject\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x33\n\nproperties\x18\x04 \x03(\x0b\x32\x1f.spl.ItemObject.PropertiesEntry\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\x12\x12\n\nupdated_at\x18\x06 \x01(\x03\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x13ValidateItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"T\n\x14ValidateItemResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x11validation_errors\x18\x03 \x03(\t\"\xb6\x01\n\x11ModifyItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12:\n\nproperties\x18\x04 \x03(\x0b\x32&.spl.ModifyItemRequest.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"^\n\x12ModifyItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\rmodified_item\x18\x03 \x01(\x0b\x32\x0f.spl.ItemObject2\xcc\x01\n\rSPLRepository\x12\x37\n\x08\x46indItem\x12\x14.spl.FindItemRequest\x1a\x15.spl.FindItemResponse\x12\x43\n\x0cValidateItem\x12\x18.spl.ValidateItemRequest\x1a\x19.spl.ValidateItemResponse\x12=\n\nModifyItem\x12\x16.spl.ModifyItemRequest\x1a\x17.spl.ModifyItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spl_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEMOBJECT_PROPERTIESENTRY']._options = None
  _globals['_ITEMOBJECT_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_MODIFYITEMREQUEST_PROPERTIESENTRY']._options = None
  _globals['_MODIFYITEMREQUEST_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_FINDITEMREQUEST']._serialized_start=26
  _globals['_FINDITEMREQUEST']._serialized_end=60
  _globals['_FINDITEMRESPONSE']._serialized_start=62
  _globals['_FINDITEMRESPONSE']._serialized_end=143
  _globals['_ITEMOBJECT']._serialized_start=146
  _globals['_ITEMOBJECT']._serialized_end=349
  _globals['_ITEMOBJECT_PROPERTIESENTRY']._serialized_start=300
  _globals['_ITEMOBJECT_PROPERTIESENTRY']._serialized_end=349
  _globals['_VALIDATEITEMREQUEST']._serialized_start=351
  _globals['_VALIDATEITEMREQUEST']._serialized_end=389
  _globals['_VALIDATEITEMRESPONSE']._serialized_start=391
  _globals['_VALIDATEITEMRESPONSE']._serialized_end=475
  _globals['_MODIFYITEMREQUEST']._serialized_start=478
  _globals['_MODIFYITEMREQUEST']._serialized_end=660
  _globals['_MODIFYITEMREQUEST_PROPERTIESENTRY']._serialized_start=300
  _globals['_MODIFYITEMREQUEST_PROPERTIESENTRY']._serialized_end=349
  _globals['_MODIFYITEMRESPONSE']._serialized_start=662
  _globals['_MODIFYITEMRESPONSE']._serialized_end=756
  _globals['_SPLREPOSITORY']._serialized_start=759
  _globals['_SPLREPOSITORY']._serialized_end=963
# @@protoc_insertion_point(module_scope)
