# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import spl_service_pb2 as spl__service__pb2


class SPLRepositoryStub(object):
    """Service definition for SPL Repository
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindItem = channel.unary_unary(
                '/spl.SPLRepository/FindItem',
                request_serializer=spl__service__pb2.FindItemRequest.SerializeToString,
                response_deserializer=spl__service__pb2.FindItemResponse.FromString,
                )
        self.ValidateItem = channel.unary_unary(
                '/spl.SPLRepository/ValidateItem',
                request_serializer=spl__service__pb2.ValidateItemRequest.SerializeToString,
                response_deserializer=spl__service__pb2.ValidateItemResponse.FromString,
                )
        self.ModifyItem = channel.unary_unary(
                '/spl.SPLRepository/ModifyItem',
                request_serializer=spl__service__pb2.ModifyItemRequest.SerializeToString,
                response_deserializer=spl__service__pb2.ModifyItemResponse.FromString,
                )


class SPLRepositoryServicer(object):
    """Service definition for SPL Repository
    """

    def FindItem(self, request, context):
        """Find an item by its ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateItem(self, request, context):
        """Validate an item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyItem(self, request, context):
        """Modify an item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SPLRepositoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindItem': grpc.unary_unary_rpc_method_handler(
                    servicer.FindItem,
                    request_deserializer=spl__service__pb2.FindItemRequest.FromString,
                    response_serializer=spl__service__pb2.FindItemResponse.SerializeToString,
            ),
            'ValidateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateItem,
                    request_deserializer=spl__service__pb2.ValidateItemRequest.FromString,
                    response_serializer=spl__service__pb2.ValidateItemResponse.SerializeToString,
            ),
            'ModifyItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyItem,
                    request_deserializer=spl__service__pb2.ModifyItemRequest.FromString,
                    response_serializer=spl__service__pb2.ModifyItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spl.SPLRepository', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SPLRepository(object):
    """Service definition for SPL Repository
    """

    @staticmethod
    def FindItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spl.SPLRepository/FindItem',
            spl__service__pb2.FindItemRequest.SerializeToString,
            spl__service__pb2.FindItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spl.SPLRepository/ValidateItem',
            spl__service__pb2.ValidateItemRequest.SerializeToString,
            spl__service__pb2.ValidateItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spl.SPLRepository/ModifyItem',
            spl__service__pb2.ModifyItemRequest.SerializeToString,
            spl__service__pb2.ModifyItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
